# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fact.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 650)
        MainWindow.setMinimumSize(QtCore.QSize(500, 650))
        MainWindow.setMaximumSize(QtCore.QSize(500, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lamp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #2a3035;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_fact = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_fact.sizePolicy().hasHeightForWidth())
        self.lbl_fact.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fact.setFont(font)
        self.lbl_fact.setStyleSheet("color: #f9f9f9;")
        self.lbl_fact.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fact.setObjectName("lbl_fact")
        self.verticalLayout.addWidget(self.lbl_fact)
        self.lbl_text = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_text.sizePolicy().hasHeightForWidth())
        self.lbl_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_text.setFont(font)
        self.lbl_text.setStyleSheet("color: #f9f9f9;")
        self.lbl_text.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_text.setWordWrap(True)
        self.lbl_text.setObjectName("lbl_text")
        self.verticalLayout.addWidget(self.lbl_text)
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btn_copy.setFont(font)
        self.btn_copy.setStyleSheet("color: #f9f9f9; background-color: rgb(81, 95, 98);")
        self.btn_copy.setObjectName("btn_copy")
        self.verticalLayout.addWidget(self.btn_copy)
        self.btn_more = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btn_more.setFont(font)
        self.btn_more.setStyleSheet("color: #f9f9f9; background-color: rgb(81, 95, 98);")
        self.btn_more.setObjectName("btn_more")
        self.verticalLayout.addWidget(self.btn_more)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_fact.setText(_translate("MainWindow", "Факт!"))
        self.lbl_text.setText(_translate("MainWindow", "Текст факта"))
        self.btn_copy.setText(_translate("MainWindow", "Скопировать факт"))
        self.btn_more.setText(_translate("MainWindow", "Ещё!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
